modLoader = "javafml"
loaderVersion = "[3,)"
#issueTrackerURL = ""
license = "Apache-2.0"

[[mods]]
modId = "coldcase"
version = "${version}"
displayName = "ColdCase"
authors = "DAQEM"
description = '''
A mod that logs all player interactions with blocks and entities and stores them in a database.
'''
#logoFile = ""

[[dependencies.coldcase]]
modId = "neoforge"
mandatory = true
versionRange = "[3,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.coldcase]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.coldcase]]
modId = "architectury"
mandatory = true
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "SERVER"

[[dependencies.coldcase]]
modId = "supermartijn642configlib"
mandatory = true
versionRange = "[${config_library_version},)"
ordering = "NONE"
side = "SERVER"

[[mixins]]
config = "coldcase-common.mixins.json"

[[mixins]]
config = "coldcase-neoforge.mixins.json"
